version: '3.9'

services:
  asir_bind_practica:
    image: internetsystemsconsortium/bind9:9.16
    ports:
    - 7000:53/tcp 
    - 7000:53/udp
    volumes:
    - configuration:/etc/bind
    - options:/var/cache/bind
    - secondaryzones:/var/lib/bind
    - logfiles:/var/log
volumes:
  configuration:
  options:
  secondaryzones:
  logfiles:
